### ISSUE TITLE
Use a $ref with https?

### ISSUE THREAD

**Issue by epugh** [hyperjump-io/json-schema.hyperjump.io#15]
I was hoping to do:

```
{
  "$id": "https://json-schema.hyperjump.io/schema",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "query_id": {
      "$ref": "https://people.apache.org/~epugh/ubi/schema/query_id.schema.json#/definitions/query_id"
    }
  }
}
```

But get the error:

```
Ud: Unable to load resource 'https://people.apache.org/~epugh/ubi/schema/query_id.schema.json#/definitions/query_id'. Referenced from 'https://json-schema.hyperjump.io/schema'.
```

**Comment by jdesrosiers** [comment]
This implementation will attempt to retrieve the schema as you expect, but it only recognizes responses with `Content-Type: application/schema+json` as JSON Schemas. Your schema uses `Content-Type: application/json`, which is why it's not working out-of-the-box for you.

Using the library, it's possible to configure this to be more lenient, but the website uses the default configuration.

You can make this work on the website by opening an second schema tab and pasting the schema you're trying to reference. The reference will resolve to the schema in that tab and doesn't need to fetch it.

**Comment by epugh** [comment]
Is this kind of conceptual flaw in making these kinds of references?  Should I not be using them?  It seems liek the right way to avoid copy/pasting over and over, but of course seems to make it harder to do the validation!

**Comment by jdesrosiers** [comment]
Actually, that's a somewhat controversial question. The current official interpretation if the JSON Schema specification is that schema identifiers are not locators despite being URIs with schemes that have locating semantics like `https:`. They only serve as an identifier for the schema and any JSON Schema library should provide some way of mapping those identifiers to schemas instead of making an HTTP request to get the schema.

So, using external schemas is not wrong, but generally you're expected to make a local copy and load it manually into the JSON schema library you're using.

Personally, I don't like that interpretation for all of the reasons you were confused by this behavior and the reasons you would like this kind of thing to work. That's why I support it in this library. However, by default it's quite strict about using media-types correctly when referencing over HTTP and a lot of schemas that are available over HTTP don't use the right media-type.

**Comment by epugh** [comment]
Thanks for sharing this.   I think I am going to back away from external schemas since I don't want to add another barrier to people using my spec by making validation more painful.  I don't have a lot of duplication anyway.
